name: chatarang
description: A chat agent that uses Dartantic.
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  all_lint_rules_community: ^0.0.43
  dartantic_ai: ^0.9.0
  dotenv: ^4.2.0
  geocoding: ^4.0.0
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
